### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by danrasmuson** [jhen0409/hyperterm-open-devtools#1]
```
Error: Cannot find module '/Users/danielrasmuson/.hyperterm_plugins/node_modules/hyperterm-open-devtools'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (/Users/danielrasmuson/hyperterm/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:47:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at eval (eval at <anonymous> (file:///Users/danielrasmuson/hyperterm/app/dist/bundle.js:2:5875), <anonymous>:101:20)
    at Array.map (native)
    at loadModules (eval at <anonymous> (file:///Users/danielrasmuson/hyperterm/app/dist/bundle.js:2:5875), <anonymous>:94:54)
    at eval (eval at <anonymous> (file:///Users/danielrasmuson/hyperterm/app/dist/bundle.js:2:5875), <anonymous>:179:1)
    at Object.<anonymous> (file:///Users/danielrasmuson/hyperterm/app/dist/bundle.js:2:5875)
```

**Comment by jhen0409** [comment]
I can't reproduce the error, could you provide your HyperTerm version?
